/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AutomationDeletePayloadInterface {
  automation_id: number;
}

export interface AutomationExpressionInterface {
  conditional_expression_id?: number;
  expression?: string;
  id?: number;
  is_else_step?: boolean;
  kind: 'if' | 'notify' | 'publish' | 'wait';
  message?: string;
  topic_id?: number;
}

export interface AutomationExpressionSetupPayloadInterface {
  automation_id: number;
  expressions: ({
    conditional_expression_id?: number;
    expression?: string;
    id?: number;
    is_else_step?: boolean;
    kind: 'if' | 'notify' | 'publish' | 'wait';
    message?: string;
    nested_expressions?: ({
      conditional_expression_id?: number;
      expression?: string;
      id?: number;
      is_else_step?: boolean;
      kind: 'notify' | 'publish' | 'wait';
      message?: string;
      topic_id?: number;
    })[];
    topic_id?: number;
  })[];
}

export interface AutomationGetPayloadInterface {
  automation_id: number;
  with_details?: boolean;
}

export interface AutomationIdInterface {
  automation_id: number;
}

export interface AutomationRunPayloadInterface {
  automation_id: number;
}

export interface AutomationInterface {
  id: number;
  is_control_shown?: boolean;
  name: string;
  position?: string;
  topic_id?: number;
  trigger: 'time' | 'sun' | 'topic' | 'user';
  trigger_at?: string;
  trigger_key?: string;
  trigger_value?: string;
}

export interface AutomationSetupPayloadInterface {
  id: number;
  is_control_shown?: boolean;
  name: string;
  position?: string;
  topic_id?: number;
  trigger: 'time' | 'sun' | 'topic' | 'user';
  trigger_at?: string;
  trigger_key?: string;
  trigger_value?: string;
}

export interface AutomationsGetPayloadInterface {}
